name: Pylint

on: 
  push:
    branches: [dev]
  pull_request:
    branches: [qa]
  workflow_dispatch:

jobs:
  pylint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint==2.6.0
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing Code with pylint
      run: |
        pylint build/ --disable=fixme --disable=R0801 --fail-under=7.0